name: netdeck_data
description: 'Netdeck Data'
version: 0.1.0
repository: https://github.com/North101/netdeck_data
publish_to: none

environment:
  sdk: '>=2.19.0-444.1.beta <3.0.0'

dependencies:
  collection: any
  drift: any
  freezed_annotation: any
  freezed: any
  json_serializable: any
  path: any
  http: ^0.13.5

dev_dependencies:
  build_runner: any
  drift_dev: any
  lints: any
